# -*- coding: utf-8 -*-
"""adult new.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SveKE87HOySJ0a-JS3D5fCbmpmsATPSw
"""

adultcsv ='/content/drive/MyDrive/adult.data.csv'
import pandas as pd
df = pd.read_csv (adultcsv)
#people of each race are represented in this dataset
race_count =df['race'].value_counts()
print (race_count)

#What is the average age of men
men_age =df[df['sex']=='Male']['age'].mean()
Women_age =df[df['sex']=='Female']['age'].mean()
print ('male ',men_age)
print ('female',Women_age)

#What is the percentage of people who have a Bachelor's degree
bachelors_degree =df[df['education']=='Bachelors']['education'].count()
total_count =len(df)
percentage1 = (bachelors_degree/total_count)*100
print(percentage1)

#What percentage of people with advanced education (Bachelors, Masters, or Doctorate) make more than 50K
education = df[((df['education'] == 'Bachelors') | (df['education'] == 'Masters') | (df['education'] == 'Doctorate')) & (df['salary'] == '>50K')]['education'].count()
percentage2 =(education/total_count)*100
print (percentage2)

#What percentage of people without advanced education make more than 50K
without_education = df['education'].loc[(df['education'] != 'Bachelors') & (df['education'] != 'Masters') & (df['education'] != 'Doctorate') & (df['salary'] == '>50K')].count()
percentage3 = (without_education/total_count)*100
print (percentage3)

#What is the minimum number of hours a person works per week
minimum_hours= df['hours-per-week'].min()
print(minimum_hours)

#What percentage of the people who work the minimum number of hours per week have a salary of more than 50K
minimum_hours_salary = df['hours-per-week'].loc[((df['hours-per-week']== minimum_hours) & (df['salary']=='>50K'))].count()
percentage4 =(minimum_hours_salary/total_count)*100
print(percentage4)

#What country has the highest percentage of people that earn >50K and what is that percentage
count_country =df['native-country'] [df['salary']=='>50K'].value_counts()
count_country_total =df['native-country'] [df['salary']=='>50K'].count()
percentage5 = (count_country/count_country_total)*100
print(percentage5)

#Identify the most popular occupation for those who earn >50K in India
occupation =df['occupation'].loc[(df['salary']=='>50K')& (df['native-country']=='India')] .value_counts()
print(occupation)